name: Result evaluation

on:
  workflow_call:
    inputs:
      os:
        description: "Current platform"
        required: true
        default: ubuntu-latest
        type: string
      size:
        description: "What dataset size to run experiments for"
        required: true
        default: "100K"
        type: choice
        options:
          - 100K
          - 300K
          - 10M
          - 30M
          - 100M

jobs:
  main:
    name: Evaluation for size = ${{ inputs.size }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Evaluate results
        shell: bash -el {0}
        run: |
          conda activate hiob
          python3 eval/eval.py
          python3 eval/plot.py --size ${{ inputs.size }} res.csv
      - uses: actions/upload-artifact@v3
        with:
          name: Results on ${{ inputs.size }}
          path: | 
            res.csv
            result_${{ inputs.size }}.png
