name: System setup

on:
  workflow_call:

jobs:
  main:
    name: System setup (${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8'
        os:
          - ubuntu-latest
        arch:
          - x64
        exclude:
          - os: macOS-latest
            arch: x86
        python-version: ["3.11.2"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Create conda environment
        shell: bash -el {0}
        run: |
          conda create -n hiob python=3.11.2
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda activate hiob
          pip install numpy
          pip install h5py
          pip install maturin
          pip install matplotlib
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build rust-search crate
        shell: bash -el {0}
        run: |
          conda activate hiob
          cd rust-search
          export RUSTFLAGS=" -C target-cpu=native -C opt-level=3"
          cargo build -r
