name: CI

on:
  workflow_dispatch:
    inputs:
      size:
        description: "What dataset size to run experiments for"
        required: true
        default: "100K"
        type: choice
        options:
          - 100K
          - 300K
          - 10M
          - 30M
          - 100M
      training_iterations:
        description: "Number of training iterations for HIOB"
        required: true
        default: 300000
        type: number
      tuning:
        description: "Whether to run in hyperparameter tuning mode"
        required: true
        default: false
        type: bool
      k:
        description: "Number of neighbors to search. Must be in [0,100]"
        required: true
        default: 10
        type: number
      nprobe_min:
        description: "Minimum number of probes on hamming distance"
        required: true
        default: 10
        type: number
      nprobe_max:
        description: "Maximum number of probes on hamming distance"
        required: true
        default: 10000
        type: number
      nprobe_steps:
        description: "Number of logarithmically interpolated probe numbers including min and max"
        required: true
        default: 11
        type: number
      bits:
        description: "Number of bits to use in binarization. Should be a multiple of 64"
        required: true
        default: 1024
        type: number
      noise:
        description: "Standard deviation of noise to add to the stochastic subsamples"
        required: true
        default: 0
        type: number

jobs:
  test:
    name: ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8'
        os:
          - ubuntu-latest
        arch:
          - x64
        exclude:
          - os: macOS-latest
            arch: x86
        python-version: ["3.11.2"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Create conda environment
        shell: bash -el {0}
        run: |
          conda create -n hiob python=3.11.2
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda activate hiob
          pip install numpy
          pip install h5py
          pip install maturin
          pip install matplotlib
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build rust-search crate
        shell: bash -el {0}
        run: |
          conda activate hiob
          cd rust-search
          export RUSTFLAGS=" -C target-cpu=native -C opt-level=3"
          cargo build -r
      - name: Run benchmark (tuning)
        if: ${{ inputs.tuning }}
        shell: bash -el {0}
        run: |
          conda activate hiob
          rust-search/target/release/rust-search \
            -i data -o result \
            --its ${{ inputs.training_iterations }} \
            --k ${{ inputs.k }} \
            --size ${{ inputs.size }} \
            --bits ${{ inputs.bits }} \
            --noise ${{ inputs.noise }} \
            --tune
      - name: Run benchmark (no tuning)
        if: ${{ !inputs.tuning }}
        shell: bash -el {0}
        run: |
          conda activate hiob
          rust-search/target/release/rust-search \
            -i data -o result \
            --its ${{ inputs.training_iterations }} \
            --k ${{ inputs.k }} \
            --size ${{ inputs.size }} \
            --bits ${{ inputs.bits }} \
            --noise ${{ inputs.noise }}
      - name: Evaluate results
        shell: bash -el {0}
        run: |
          conda activate hiob
          python3 eval/eval.py
          python3 eval/plot.py --size ${{ inputs.size }} res.csv
      - uses: actions/upload-artifact@v3
        with:
          name: Results on ${{ inputs.size }}
          path: | 
            res.csv
            result_${{ inputs.size }}.png
